version: b{build}
pull_requests:
  do_not_increment_build_number: true

clone_depth: 10
image: Visual Studio 2017
configuration: Release

max_jobs: 5

environment:
  CODECOV_TOKEN:
    secure: WvLTLCfMjt4v4RqYBY5L3DUR7CLmrMBhYz4PYbjpFzGIBMCFaTYy5P/ppPqNnhu/

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cmd: git submodule update --init --recursive
  - cmd: choco install opencover.portable -y
  - cmd: choco install codecov -y

before_build:
  - cmd: nuget restore -verbosity quiet

build:
  parallel: true
  verbosity: minimal
  project: Pisstaube

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full Pisstaube.Tests/Pisstaube.Tests.csproj" -output:"coverage.xml" -filter:"+[Pisstaube*]* -[Pisstaube.Tests*]*" -oldstyle -filter:"+[*]* -[*]*.Migrations.*"

after_test:
  - codecov -f .\coverage.xml -t $(codecov_token)
